import { useState } from 'react'
import { Breadcrumbs } from '../components/Breadcrumbs'
import { StatusSelect } from '../components/StatusSelect'
import type { LookbookEntry, Role, Scene } from '../models/lookbook'

export function MasterSceneListPage({ scenes, entries, role, onHome, onChange }: { scenes: Scene[]; entries: LookbookEntry[]; role: Role; onHome: () => void; onChange: (scenes: Scene[]) => void }) {
  const [editingId, setEditingId] = useState<string>()
  const [draft, setDraft] = useState<Scene>()
  const labels = (ids: string[]) => ids.map((id) => entries.find((entry) => entry.id === id)?.title).filter(Boolean).join(', ') || '—'
  const start = (scene: Scene) => { setEditingId(scene.id); setDraft(structuredClone(scene)) }
  const save = () => { if (draft) onChange(scenes.map((scene) => scene.id === draft.id ? draft : scene)); setEditingId(undefined) }
  const add = () => { const next = Math.max(0, ...scenes.map((scene) => scene.number)) + 1; const scene: Scene = { id: crypto.randomUUID(), number: next, title: '', characterIds: [], locationIds: [], notes: '', status: 'draft' }; onChange([...scenes, scene]); start(scene) }
  return <main className="page-shell"><Breadcrumbs items={[{ label: 'Home', onClick: onHome }, { label: 'Master Scene List' }]} /><div className="page-heading"><div><p className="eyebrow">CHRONOLOGICAL</p><h1>Master Scene List</h1></div>{role === 'editor' && <button className="button button-accent" onClick={add}>Add scene</button>}</div><div className="timeline">{[...scenes].sort((a, b) => a.number - b.number).map((scene) => editingId === scene.id && draft ? <article key={scene.id} className="scene-edit"><label>Scene number<input type="number" value={draft.number} onChange={(event) => setDraft({ ...draft, number: Number(event.target.value) })} /></label><label>Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><StatusSelect value={draft.status} onChange={(status) => setDraft({ ...draft, status })} /><label>Notes<textarea value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} /></label><div className="check-grid"><h3>Characters</h3>{entries.filter((entry) => entry.type === 'character').map((entry) => <label key={entry.id}><input type="checkbox" checked={draft.characterIds.includes(entry.id)} onChange={() => setDraft({ ...draft, characterIds: draft.characterIds.includes(entry.id) ? draft.characterIds.filter((id) => id !== entry.id) : [...draft.characterIds, entry.id] })} />{entry.title}</label>)}<h3>Locations</h3>{entries.filter((entry) => entry.type === 'location').map((entry) => <label key={entry.id}><input type="checkbox" checked={draft.locationIds.includes(entry.id)} onChange={() => setDraft({ ...draft, locationIds: draft.locationIds.includes(entry.id) ? draft.locationIds.filter((id) => id !== entry.id) : [...draft.locationIds, entry.id] })} />{entry.title}</label>)}</div><button className="button button-accent" onClick={save}>Save scene</button><button className="button" onClick={() => setEditingId(undefined)}>Cancel</button></article> : <article key={scene.id}><div className="scene-number">{scene.number}</div><div><div className="scene-title"><h2>{scene.title || `Scene ${scene.number}`}</h2><span className={`status-pill status-${scene.status}`}>{scene.status}</span></div><dl><dt>Characters</dt><dd>{labels(scene.characterIds)}</dd><dt>Locations</dt><dd>{labels(scene.locationIds)}</dd>{scene.notes && <><dt>Notes</dt><dd>{scene.notes}</dd></>}</dl>{role === 'editor' && <button className="text-button" onClick={() => start(scene)}>Edit scene</button>}</div></article>)}</div></main>
}
